on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    environment: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            binary-caches = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
      - name: Set up Cachix caching
        uses: cachix/cachix-action@v12
        with:
          name: ${{ secrets.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Use your cross-platform dev environment somehow

      # Maybe also build your packages using Nix

      - name: Cache dev environment
        run: |
          nix develop --profile cachix-github-actions-example
          cachix push ${{ secrets.CACHIX_CACHE }} cachix-github-actions-example
      - name: Cache package builds
        run: |
          nix build --json \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push ${{ secrets.CACHIX_CACHE }}
